/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 houseLights.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/houseLights.glb')
  return (
    <group {...props} dispose={null}>
      <instancedMesh args={[nodes.HouseLights.geometry, materials.DoorLights, 94]} instanceMatrix={nodes.HouseLights.instanceMatrix} position={[-4.918, 0.89, -2.632]} rotation={[Math.PI, -0.912, Math.PI]} />
    </group>
  )
}

useGLTF.preload('/houseLights.glb')
